### ISSUE TITLE
Output from Pitch detection methods

### ISSUE THREAD

**Issue by demartsev** [tatters/soundgen#4]
Is there a ways to add the values of AUTOCOR pitch detection to the output of the ANALYZE function? I can not seem to figure how to achieve that. 

Another minor issues with the _voicedSeparate = F_ option. It does not seem to have any effect on the output. The Voiced columns are still there. 

Thanks!

**Comment by tatters** [comment]
The AUTOCOR pitch estimate is not returned separately in the current soundgen version (each pitch tracker used to return its own separate output before, but that proved a bit confusing, so I have since removed those columns). However, you can "isolate" it by setting `pitchMethods = 'autocor'` - if autocorrelation is the only pitch tracking method, the column "pitch" will give you the output of AUTOCOR algorithm.
You're right about `voicedSeparate = F `, thanks for pointing it out! I think I'll just deprecate this argument in the next version since it's probably not so useful anyway.

**Comment by demartsev** [comment]
Got it! Thanks a lot for a quick response 👍

**Comment by tatters** [comment]
No problem! A little clarification about `voicedSeparate = F`: it does set all "...Voiced" columns to NA in analyzeFolder, but like I said, I'm going to remove it in any case.
